SET LINESIZE 200
SET PAGESIZE 60

COLUMN StudentID          FORMAT 99
COLUMN SectionID          FORMAT 99
COLUMN CourseID           FORMAT 99
COLUMN ProfessorID        FORMAT 99
COLUMN StudentFirstName   FORMAT A10
COLUMN StudentLastName    FORMAT A10
COLUMN PercentGrade       FORMAT 999
COLUMN SectionName        FORMAT A15
COLUMN CourseName         FORMAT A7
COLUMN ProfessorFirstName FORMAT A10
COLUMN ProfessorLastName  FORMAT A10

SELECT * FROM StudentManagement;

SET LINESIZE 80
