--------------------------------------------------------
--  File created - Friday-November-15-2024   
--------------------------------------------------------
REM INSERTING into SYSTEM.FEE
SET DEFINE OFF;
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (1,'Deposit','Justin paid Deposit Fee',to_date('02-FEB-23','DD-MON-RR'),50,1,1);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (2,'Discount','Justin paid Discount Fee',to_date('02-FEB-23','DD-MON-RR'),-30,1,2);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (3,'Discount','Justin paid Rate Fee',to_date('02-FEB-23','DD-MON-RR'),40,1,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (4,'Discount','Justin paid Rate Fee',to_date('08-FEB-23','DD-MON-RR'),40,1,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (5,'Discount','Justin paid Rate Fee',to_date('17-FEB-23','DD-MON-RR'),40,1,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (6,'Discount','Justin paid Rate Fee',to_date('27-FEB-23','DD-MON-RR'),40,1,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (7,'Discount','Justin paid Deposit Fee',to_date('27-FEB-23','DD-MON-RR'),-20,1,1);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (8,'Deposit','Kristoff paid Deposit Fee',to_date('03-FEB-23','DD-MON-RR'),40,2,1);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (9,'Deposit','Kristoff paid Rate Fee',to_date('03-FEB-23','DD-MON-RR'),50,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (10,'Deposit','Kristoff paid Rate Fee',to_date('04-FEB-23','DD-MON-RR'),50,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (11,'Deposit','Kristoff paid Rate Fee',to_date('05-FEB-23','DD-MON-RR'),50,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (12,'Deposit','Kristoff paid Rate Fee',to_date('06-FEB-23','DD-MON-RR'),50,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (13,'Deposit','Kristoff paid Rate Fee',to_date('07-FEB-23','DD-MON-RR'),50,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (14,'Deposit','Kristoff paid Rate Fee',to_date('08-FEB-23','DD-MON-RR'),50,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (15,'Deposit','Kristoff paid Rate Fee',to_date('09-FEB-23','DD-MON-RR'),50,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (16,'Deposit','Kristoff paid Rate Fee',to_date('10-FEB-23','DD-MON-RR'),50,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (17,'Deposit','Kristoff paid Rate Fee',to_date('11-FEB-23','DD-MON-RR'),60,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (18,'Deposit','Kristoff paid Rate Fee',to_date('12-FEB-23','DD-MON-RR'),60,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (19,'Deposit','Kristoff paid Rate Fee',to_date('13-FEB-23','DD-MON-RR'),60,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (20,'Deposit','Kristoff paid Rate Fee',to_date('14-FEB-23','DD-MON-RR'),60,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (21,'Deposit','Kristoff paid Rate Fee',to_date('15-FEB-23','DD-MON-RR'),60,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (22,'Deposit','Kristoff paid Rate Fee',to_date('16-FEB-23','DD-MON-RR'),60,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (23,'Deposit','Kristoff paid Rate Fee',to_date('17-FEB-23','DD-MON-RR'),60,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (24,'Deposit','Kristoff paid Rate Fee',to_date('17-FEB-23','DD-MON-RR'),20,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (25,'Deposit','Kristoff paid Rate Fee',to_date('17-FEB-23','DD-MON-RR'),30,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (26,'Deposit','Kristoff paid Rate Fee',to_date('17-FEB-23','DD-MON-RR'),-40,2,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (27,'Deposit','Billy paid Deposit Fee',to_date('20-JAN-23','DD-MON-RR'),0,3,1);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (28,'Deposit','Billy paid Rate Fee',to_date('20-JAN-23','DD-MON-RR'),30,3,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (29,'Deposit','Deena paid Deposit Fee',to_date('01-JAN-23','DD-MON-RR'),0,4,1);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (30,'Deposit','Deena paid Rate Fee',to_date('01-JAN-23','DD-MON-RR'),0,4,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (31,'Deposit','Deena paid Deposit Fee',to_date('01-FEB-23','DD-MON-RR'),0,4,1);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (32,'Deposit','Deena paid Rate Fee',to_date('01-FEB-23','DD-MON-RR'),0,4,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (33,'Deposit','Deena paid Deposit Fee',to_date('01-MAR-23','DD-MON-RR'),0,4,1);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (34,'Deposit','Deena paid Rate Fee',to_date('01-MAR-23','DD-MON-RR'),0,4,3);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (35,'Deposit','Deena paid Deposit Fee',to_date('01-APR-23','DD-MON-RR'),0,4,1);
Insert into SYSTEM.FEE (FEEID,FEENAME,FEEDESCRIPTION,DATECHARGED,FEECHARGED,GUESTID,FEETYPEID) values (36,'Deposit','Deena paid Rate Fee',to_date('01-APR-23','DD-MON-RR'),0,4,3);
