-- Step 1: Add primary key constraints to parent tables
ALTER TABLE CUSTOMER
ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (CustomerID);

ALTER TABLE PRODUCT
ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (ProductID);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EmployeeID);

-- Step 2: Add primary key constraint to the PURCHASE table
ALTER TABLE PURCHASE
ADD CONSTRAINT PK_PURCHASE PRIMARY KEY (PurchaseID);

-- Step 3: Add foreign key constraints to PURCHASE
ALTER TABLE PURCHASE
ADD CONSTRAINT FK_PURCHASE_CUSTOMER
FOREIGN KEY (CustomerID)
REFERENCES CUSTOMER (CustomerID);

ALTER TABLE PURCHASE
ADD CONSTRAINT FK_PURCHASE_PRODUCT
FOREIGN KEY (ProductID)
REFERENCES PRODUCT (ProductID);

ALTER TABLE PURCHASE
ADD CONSTRAINT FK_PURCHASE_EMPLOYEE
FOREIGN KEY (EmployeeID)
REFERENCES EMPLOYEE (EmployeeID);
